---
- name: Update & Upgrade Package
  ansible.builtin.apt:
    update_cache: true # similar to sudo apt-get update
    upgrade: dist # similar to sudo apt-get upgrade
    state: present

- name: Install Dependencies
  ansible.builtin.apt:
    update_cache: true # similar to sudo apt-get update
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present # make sure everything is installed
