---
- name: Update & Upgrade Package
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    update_cache: true
    state: present

- name: Create Directory for GPG Signing-key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
