---
- name: Master node setup
  ansible.builtin.include_tasks: master.yaml
  when: "'master' in group_names"

- name: Worker node setup
  ansible.builtin.include_tasks: worker.yaml
  when: "'workers' in group_names"
