---
- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true

- name: Disable swap (kubelet requires swap off)
  ansible.builtin.command:
    cmd: swapoff -a
  register: disable_swap_output
  changed_when: false

- name: Initialize Kubernetes master
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output
  changed_when: false

- name: Set up kubectl for the current user
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "mkdir -p $HOME/.kube"
    - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
    - "chown $(id -u):$(id -g) $HOME/.kube/config"
  register: kubectl_setup_output
  changed_when: false

- name: Install Calico network plugin
  ansible.builtin.command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: "'calico' in kubeadm_output.stdout"
  register: calico_install_output
  changed_when: false
