---
- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true

- name: Disable swap (kubelet requires swap off)
  ansible.builtin.command:
    cmd: swapoff -a
  register: disable_swap_output
  changed_when: false

- name: Join worker nodes to the cluster
  ansible.builtin.command: "{{ hosts['master']['kubeadm_output']['stdout_lines'][0] }}"
  when: "'kubeadm join' in hosts['master']['kubeadm_output']['stdout']"
  register: join_worker_node_output
  changed_when: false
