---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
  namespace: default
  labels:
    app: go-hello-world
spec:
  selector:
    matchLabels:
      app: go-hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      automountServiceAccountToken: False
      containers:
        - name: go-hello-world
          image: yobubble62/go-hello-world:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 7070
              name: go-hello-world
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-service
  namespace: default
spec:
  selector:
    app: go-hello-world
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: go-hello-world
      protocol: TCP
      port: 80
      targetPort: 7070
      # nodePort:
