---
- name: Setup Docker and Kuberntes on Ubuntu Server 24.04
  hosts: target
  become: true
  remote_user: ubuntu
  roles:
    - config # run all the config tasks
    - docker # run all the docker tasks
    - kubernetes # run all the kubernetes tasks
