---
- name: Docker and Kubernetes Installation on servers
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - config # run all the config tasks
    - docker # run all the docker tasks
    - kubernetes # run all the kubernetes tasks
